DATASET_SPLIT_PERCENTAGE = 0.2
TRAIN_TEST_SPLIT = 0.95

#yamls
CONFIG_YAML = "config/config.yaml"
PARAMS_YAML = "params.yaml"
SCHEMA_YAML = "schema.yaml"

#aws
AWS_BUCKET = "bsaarun54.summarizer"

RUN_FROM_LOCAL = True

#model trainer
# training args 
BATCH_SIZE = 5
NUM_TRAIN_EPOCHS = 1
LEARNING_RATE = 5.6e-5
WEIGHT_DECAY = 0.01
SAVE_TOTAL_LIMIT = 3
PREDICT_WITH_GENERATE = True
PUSH_TO_HUB = False
REPORT_TO = "none"
FP16 = True
GRADIENT_ACCUMULATION_STEPS = 8

#text_summarizer
MAX_INPUT_LENGTH = 512
STRIDE = 64
NUM_BEAMS = 4
LENGTH_PENALTY = 2.0
MAX_LENGTH = 150
MIN_LENGTH = 30
NO_REPEAT_NGRAM_SIZE = 2
EARLY_STOPPING = True

#pipeline task
PIPELINE = "predict"
